// Auto-generated main function for local development
// This file is generated by the #[route] macro and should not be edited manually

use std::env;

fn main() {
    // Check if this is a function call from the local development server
    if let Ok(mode) = env::var("RUSTEZE_MODE") {
        if mode == "function_call" {
            if let Ok(function_name) = env::var("RUSTEZE_FUNCTION") {
                match function_name.as_str() {
                    "get_bar_handler" => {
                        let result = get_bar_handler();
                        println!("{}", result);
                        return;
                    }
                    "get_foo_handler" => {
                        let result = get_foo_handler();
                        println!("{}", result);
                        return;
                    }
                    "get_hello_handler" => {
                        let word = env::var("RUSTEZE_PARAM_WORD").unwrap_or_else(|_| "World".to_string());
                        let result = get_hello_handler(word);
                        println!("{}", result);
                        return;
                    }
                    _ => {
                        eprintln!("Unknown function: {}", function_name);
                        std::process::exit(1);
                    }
                }
            }
        }
    }
    
    // Default behavior - just print that functions are registered
    println!("Rusteze functions registered for local development");
}
