// Auto-generated callable functions for local development
// This file is generated by the #[route] macro and should not be edited manually

use std::collections::HashMap;

/// Call the get_bar_handler function with the given parameters
pub fn call_get_bar_handler(params: HashMap<String, String>) -> Result<String, String> {
    // Extract parameters based on the function signature
    let word = params.get("word").unwrap_or(&"World".to_string()).clone();
    
    // Call the actual annotated function directly
    // This assumes the function is available in the current crate's main module
    let result = crate::get_bar_handler(word);
    Ok(result)
}

/// Get registration info for get_bar_handler
pub fn get_get_bar_handler_info() -> (&'static str, &'static str, &'static str) {
    ("get_bar_handler", "GET", "/bar")
}

/// Call the get_foo_handler function with the given parameters
pub fn call_get_foo_handler(params: HashMap<String, String>) -> Result<String, String> {
    // Extract parameters based on the function signature
    let word = params.get("word").unwrap_or(&"World".to_string()).clone();
    
    // Call the actual annotated function directly
    // This assumes the function is available in the current crate's main module
    let result = crate::get_foo_handler(word);
    Ok(result)
}

/// Get registration info for get_foo_handler
pub fn get_get_foo_handler_info() -> (&'static str, &'static str, &'static str) {
    ("get_foo_handler", "GET", "/brad")
}

/// Call the get_hello_handler function with the given parameters
pub fn call_get_hello_handler(params: HashMap<String, String>) -> Result<String, String> {
    // Extract parameters based on the function signature
    let word = params.get("word").unwrap_or(&"World".to_string()).clone();
    
    // Call the actual annotated function directly
    // This assumes the function is available in the current crate's main module
    let result = crate::get_hello_handler(word);
    Ok(result)
}

/// Get registration info for get_hello_handler
pub fn get_get_hello_handler_info() -> (&'static str, &'static str, &'static str) {
    ("get_hello_handler", "GET", "/test/{word}")
}

/// Get all registered functions for local development
pub fn get_all_functions() -> Vec<(&'static str, fn(HashMap<String, String>) -> Result<String, String>)> {
    vec![
        ("get_bar_handler", call_get_bar_handler),
        ("get_foo_handler", call_get_foo_handler),
        ("get_hello_handler", call_get_hello_handler),
    ]
}
